### ISSUE TITLE
Pretrained model not available.

### ISSUE THREAD

**Issue by harshakokel** [guenthermi/table-embeddings#1]
Hello @guenthermi, 

We are not able to access pre-trained models 

https://wwwdb.inf.tu-dresden.de/misc/web-table-embeddings/web_table_embeddings_combo64.bin.gz

Can you point to an updated link? 

Regards,
Harsha

**Comment by guenthermi** [comment]
Hi, sorry, for the late response, the university could not host the models anymore on there Web server. Therefore, I republished them on their huggingface page. The model you are searching for is now available at: https://huggingface.co/ddrg/web_table_embeddings_combo64

I also made some small adjustments to load the models directly from huggingface and install the embedding module via pip

**Comment by harshakokel** [comment]
Thank you.
